version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: products_db
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  products-service:
    build: ./products-service
    container_name: products-service
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "3002:3002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://products_inventory_db:5432/inventorydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - PRODUCTS_API_URL=http://products-service:3001/products
      - PRODUCTS_API_KEY=123456
      - INTERNAL_API_KEY=123456
    depends_on:
      - products-service
      - products_inventory_db

  products_inventory_db:
    image: postgres:15
    container_name: products_inventory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventorydb
    ports:
      - "5440:5432"
    volumes:
      - inventory-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  inventory-data:
